<?xml version="1.0"?>
<robot name="dome_x1" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Parameters -->
  <xacro:property name="plate_diameter" value="0.280" />
  <xacro:property name="plate_thickness" value="0.003" />
  <xacro:property name="bottom_plate_height" value="0.065" />
  <xacro:property name="top_plate_height" value="0.125" />
  <xacro:property name="base_link_x_offset" value="0.085" />
  <xacro:property name="wheel_base" value="0.215" />
  <xacro:property name="wheel_diameter" value="0.0625" />
  <xacro:property name="wheel_width" value="0.024" />
  <xacro:property name="support_post_diameter" value="0.010" />
  <xacro:property name="support_post_height" value="0.080" />
  <xacro:property name="laser_x_offset" value="-0.040" />
  <xacro:property name="laser_z_offset" value="0.130" />
  <xacro:property name="imu_x_offset" value="-0.040" />
  <xacro:property name="imu_z_offset" value="0.020" />
  <xacro:property name="front_marker_x_offset" value="0.015" />
  <xacro:property name="front_marker_z_offset" value="0.050" />

  <!-- Materials -->
  <material name="clear_acrylic">
    <color rgba="0.8 0.8 1.0 0.6"/>
  </material>

  <material name="blue">
    <color rgba="0.0 0.0 1.0 1.0"/>
  </material>

  <material name="light_blue">
    <color rgba="0.5 0.8 1.0 1.0"/>
  </material>

  <material name="grey">
    <color rgba="0.5 0.5 0.5 1.0"/>
  </material>

  <material name="red">
    <color rgba="1.0 0.0 0.0 1.0"/>
  </material>

  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>

  <!-- Base footprint (ground projection) -->
  <link name="base_footprint">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.01 0.01 0.001"/>
      </geometry>
      <material name="grey"/>
    </visual>
  </link>

  <!-- Base link (main robot body) -->
  <link name="base_link"/>
  <joint name="base_link_to_base_footprint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="${-base_link_x_offset} 0 ${-bottom_plate_height}" rpy="0 0 0"/>
  </joint>

  <!-- Bottom plate -->
  <link name="bottom_plate">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${plate_diameter/2}" length="${plate_thickness}"/>
      </geometry>
      <material name="clear_acrylic"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${plate_diameter/2}" length="${plate_thickness}"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_link_to_bottom_plate" type="fixed">
    <parent link="base_link"/>
    <child link="bottom_plate"/>
    <origin xyz="${-base_link_x_offset} 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Top plate -->
  <link name="top_plate">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${plate_diameter/2}" length="${plate_thickness}"/>
      </geometry>
      <material name="clear_acrylic"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${plate_diameter/2}" length="${plate_thickness}"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_link_to_top_plate" type="fixed">
    <parent link="base_link"/>
    <child link="top_plate"/>
    <origin xyz="${-base_link_x_offset} 0 ${top_plate_height - bottom_plate_height}" rpy="0 0 0"/>
  </joint>

  <!-- Support post macro -->
  <xacro:macro name="support_post" params="name x_pos y_pos">
    <link name="${name}">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${support_post_diameter/2}" length="${support_post_height}"/>
        </geometry>
        <material name="blue"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${support_post_diameter/2}" length="${support_post_diameter}"/>
        </geometry>
      </collision>
    </link>

    <joint name="base_link_to_${name}" type="fixed">
      <parent link="base_link"/>
      <child link="${name}"/>
      <origin xyz="${x_pos} ${y_pos} ${(top_plate_height - bottom_plate_height)/2}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>

  <!-- Support posts -->
  <xacro:support_post name="support_post_1" x_pos="0.040" y_pos="0"/>
  <xacro:support_post name="support_post_2" x_pos="-0.140" y_pos="0.070"/>
  <xacro:support_post name="support_post_3" x_pos="-0.140" y_pos="-0.070"/>

  <!-- Wheel macro -->
  <xacro:macro name="wheel" params="side reflect">
    <link name="${side}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="1.57 0 0"/>
        <geometry>
          <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="1.57 0 0"/>
        <geometry>
          <cylinder radius="${wheel_diameter/2}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="base_link_to_${side}_wheel" type="continuous">
      <parent link="base_link"/>
      <child link="${side}_wheel"/>
      <origin xyz="0 ${reflect * wheel_base/2} ${-wheel_diameter/2 - 0.005}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- Wheels -->
  <xacro:wheel side="left" reflect="1"/>
  <xacro:wheel side="right" reflect="-1"/>

  <!-- laser -->
  <link name="laser">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.025" length="0.040"/>
      </geometry>
      <material name="light_blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.025" length="0.040"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_link_to_laser" type="fixed">
    <parent link="base_link"/>
    <child link="laser"/>
    <origin xyz="${laser_x_offset} 0 ${laser_z_offset}" rpy="0 0 ${-pi/2}"/>
  </joint>

  <!-- IMU -->
  <link name="imu">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.020 0.020 0.010"/>
      </geometry>
      <material name="grey"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.020 0.020 0.010"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_link_to_imu" type="fixed">
    <parent link="base_link"/>
    <child link="imu"/>
    <origin xyz="${imu_x_offset} 0 ${imu_z_offset}" rpy="0 0 0"/>
  </joint>

  <!-- Front marker -->
  <link name="front_marker">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.10 0.030 0.010"/>
      </geometry>
      <material name="red"/>
    </visual>
  </link>

  <joint name="base_link_to_front_marker" type="fixed">
    <parent link="base_link"/>
    <child link="front_marker"/>
    <origin xyz="${front_marker_x_offset} 0 ${front_marker_z_offset}" rpy="0 0 0"/>
  </joint>

</robot>